name: Emanate Design
favicon: null
layout_spectrum: 0.6916556681971997
typography_spectrum: 0.5906983444001526
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.02183282421901822
  lightness: 0.8828263154719025
  saturation: 0.6388946867082268
  rhythmicContrast: 0.6008575896266848
purpose: []
